# Generated by Django 4.2 on 2024-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0006_alter_dodatkoweinfo_gatunek_aktor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktor',
            name='filmy',
            field=models.ManyToManyField(related_name='aktorzy', to='filmyweb.film'),
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (0, 'Inne'), (2, 'Komedia'), (3, 'Sci-fi'), (1, 'Horror')], default=0),
        ),
    ]
